# Generated by Django 3.2.4 on 2021-06-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('person_name', models.CharField(db_column='person_name', default='', max_length=100)),
                ('person_email', models.EmailField(db_column='person_email', default='', max_length=250)),
                ('person_balance', models.FloatField(db_column='person_balance')),
                ('person_account_number', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'person_table',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('receiver_amount', models.FloatField(verbose_name='receiver_amount')),
                ('receiver_id', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='creatingmodals.person')),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='creatingmodals.person')),
            ],
            options={
                'db_table': 'transaction_table',
            },
        ),
    ]
